---
abstract: 'Interface for manipulating ar archives with libarchive'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Module::Build: '0.3601'
  Test::MockObject: '0'
  Test::More: '0.94'
configure_requires:
  Alien::Libarchive: '0.20'
  ExtUtils::CChecker: '0'
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Archive-Ar-Libarchive
requires:
  Alien::Libarchive: '0'
  File::Basename: '0'
  Math::Int64: '0.28'
  base: '0'
  perl: '5.008'
resources:
  bugtracker: https://github.com/plicease/Archive-Ar-Libarchive/issues
  homepage: http://perl.wdlabs.com/Archive-Ar-Libarchive
  repository: git://github.com/plicease/Archive-Ar-Libarchive.git
version: '2.05'
